### ISSUE TITLE
Создание ноутбуков из md файлов

### ISSUE THREAD

**Issue by alexey-pronkin** [quantum-ods/qmlcourse#407]
Некоторые лекции не конвертируются в ноутбуки с помощью 
`call(['poetry', 'run', 'jupytext', 'qmlcourse'+'/' + chapter['file'], '--to', 'ipynb'])`

Например,
```
 raise InconsistentPath(
jupytext.paired_paths.InconsistentPath: 'qmlcourse/book/ml/ru/ml_intro' is not a notebook. Supported extensions are '.ipynb', '.md', '.markdown', '.Rmd', '.py', '.coco', '.R', '.r', '.jl', '.cpp', '.ss', '.clj', '.scm', '.sh', '.ps1', '.q', '.m', '.pro', '.js', '.ts', '.scala', '.rs', '.robot', '.resource', '.cs', '.fsx', '.fs', '.sos', '.java', '.groovy', '.sage', '.ml', '.hs', '.tcl', '.mac', '.qmd', '.myst', '.mystnb', '.mnb'
```

**Comment by vtrokhymenko** [comment]
но jb рисует ведь https://quantum-ods.github.io/qmlcourse/book/ml/ru/ml_l1.html или о чём ты? где именно эта ошибка возникает?

**Comment by alexey-pronkin** [comment]
эту он и у меня конвертирует. Вот, например, md файл о блоке не конвертируется. Так же как и в веб версии:
![Screenshot from 2022-06-16 22-46-39](https://user-images.githubusercontent.com/31882933/174152489-8c355ce8-77cd-443e-9397-78f3d1eecf42.png)

**Comment by alexey-pronkin** [comment]
Таких лекций много, например, https://quantum-ods.github.io/qmlcourse/book/problems2qml/ru/qubo_linreg_svm_kmeans.html тоже не конвертит. Формат нарушен. Я пока не нашел в чем проблема вообще.

**Comment by vtrokhymenko** [comment]
мб в том, что нет (см. ниже), можешь проверить?

```
---
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
kernelspec:
  display_name: Python 3
  language: python
  name: python3
---
```
